name: WhatDevice
version: '${version}'
main: me.miguelcr.whatdevice.WhatDevice
api-version: 1.18
depend: [ floodgate ]
authors: [ MiguelX413 ]
description: Find out what device a Floodgate player is on
website: https://miguelcr.me
commands:
  device:
    description: Find a Floodgate player's device
    usage: /device [Player]
permissions:
  whatdevice.*:
    default: op
    description: Give players with op everything by default
  whatdevice.device:
    default: op
    description: Allows the user to run /device on theirself
  whatdevice.device.others:
    default: op
    description: Allows the user to run /device on others
    children:
      whatdevice.device: true
